### ISSUE TITLE
Warp failed for DTM

### ISSUE THREAD

**Issue by ShebMichel** [Loop3D/map2loop#41] opened 2024-02-23 02:23 UTC
I am getting the bellow error message while running map2loop via docker compose:

Unused keys from legacy format ['deposit_dist', 'fdipdir_flag', 'ftype', 'mcom', 'minf', 'msc', 'mscm', 'msn', 'mst', 'mtc', 'o-geol']
Datatype FAULT_ORIENTATION is not set and so cannot be loaded
Error in docker terminal:  Warp failed for DTM

##Here is the error in the QGIS terminal
Error in QGIS terminal: Failed to process SRS definition: EPSG:28350

Any clue

**Comment by lachlangrose** [comment] 2024-02-23 02:32
Hi @ShebMichel,

Without an actual example or a minimal working example its not very easy to solve your problem. Have you tried to replicate the issue in Python outside of QGIS? It could be possible the error is coming from the QGIS interface and not from map2loop? are you using the most recent version of map2loop? 

What coordinate systems are you converting between? The error text seems to suggest that the reprojection is failing... is it possible that you are trying to get it to do an invalid reprojection?

Why are you using the legacy keys? You should be using the updated dictionary. See[ here](https://github.com/Loop3D/map2loop/blob/master/map2loop/config.py)

**Comment by ShebMichel** [comment] 2024-02-23 02:48
map2loop 3 (recent version)
replicate outside QGIS: Yes, the same example even in a local environment works fine.
Error from QGIS: No, the same data have been tested using the previous map2loop and run well without error.  
I am testing without changing anything this example: Example 3 - Local Source Data.ipynb @https://github.com/Loop3D/map2loop-3-notebooks under the map2loop docker container via Docker Desktop and fails with the above-mentioned error.

**Comment by lachlangrose** [comment] 2024-02-23 02:51
@ShebMichel from what you have said Example 3 works in map2loop-3... so the issue isn't in map2loop?

**Comment by lachlangrose** [comment] 2024-02-23 02:58
@ShebMichel you need to test whether the notebooks work within the python environment on your docker image. GDAL errors aren't really issues with map2loop but are issues with the setup of your environment.

**Comment by lachlangrose** [comment] 2024-02-23 05:11
I'm closing this issue, feel free to reopen with an example showing the bug in map2loop.

**Closed as completed** 2024-02-23 05:11 UTC
